name: Deploy Notebooks to GH Pages
on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Convert Notebooks to HTML
        run: |
          mkdir public
          # Added --tag-format='' to help with widget issues 
          # and specifically added --no-prompt to clean up the look
          jupyter nbconvert --to html \
            --template lab \
            --no-input \
            --output-dir='public' \
            01-practical-deep-learning-for-coders/*.ipynb \
            02-deep-learning-foundations-to-stable-diffusion/*.ipynb || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # This must match the folder where your HTML files are
          path: 'public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4